import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main
          className="
          flex
          min-h-full
          flex-col
          justify-center
          items-center
          py-12
          sm:px-6
          lg:px-8
        "
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
